### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by GRA0007** [stevent-team/epoxy#17]
Epoxy should cache routes that are visited to avoid repeated database calls for the same route in a short time frame.

**Comment by GRA0007** [comment]
Note: this currently wouldn't work well with our usage as we need to check the user agent in the route handler, I propose that instead of the route being set to a function in the returned object, it can also instead be set to an object that has a `condition` property that is a function that must return true to continue, that isn't cached, and then a `handler` property that the result of is cached.

Alternatively we could have a `condition` function for all the routes, that also receives the route and works the same way

**Comment by giraugh** [comment]
I was thinking something similar where the result from the epoxy config is an array of objects with handlers. However, instead of the `condition` property, I was thinking a `key` property. That `key` property is a function with the signature `Express.Request -> [any]`. Then we cache against the result from that function.

So for example, in stevent we could have
```js
export default {
  '/event/:eventid': {
     handler: eventDetailHandler,
     key: req => [req.params?.eventid, req.get('User-Agent')]
  }
}
```
